
Go 语言引入了三个函数来进行异常错误的处理，即 defer(), panic() recover() 。

### defer

defer 的作用是推迟 defer 关键字下的语句，直到函数结束时才会被调用。如果这条语句后面的语句运行时发生了异常，defer 关键字下的语句仍然会被执行。

defer 通常用于资源的释放，示例如下:
```go
    func CopyFile(dst, src string) (w int64, err error) {
        srcFile, err := os.Open(src)
        if err != nil {
            return
        }
        defer srcFile.Close()

        dstFile, err := os.Create(dstName)
        if err != nil {
            return
        }
        defer dstFile.Close()

        return io.Copy(dstFile, srcFile)
    }
```
上述代码中，即使 CopyFile 函数抛出异常，仍然可以保证 dstFile 和 srcFile 会被正常关闭。

defer 语句的调用遵照先进后出原则，即最后一个 defer 语句将最先被执行。

如果需要处理的东西太多，也可以通过 defer 构造匿名函数:
```go
    defer func() {
        // more clear
    }
```

注意，defer 关键字下的语句是直到所在的函数执行完毕时执行，而不是出作用域执行。

[defer出函数才执行](t/07_defer.go)

根据 defer 延迟执行的特性，可以利用它来计算代码块的执行时间。

[使用defer计算函数执行时间](t/07_defer_time_cost.go)

### panic

panic() 函数常用在出现不可恢复错误的地方，如缓冲区溢出、数组越界、空指针异常等。

panic() 函数定义如下:
```go
    func panic(v interface{})
```
该函数接受任何值作为参数，一旦执行就会终止程序运行。由于运行 panic() 函数会造成程序崩溃，所以一般开发人员不愿意看到 panic 异常的情况，然而这无法避免，为此 Go 提供了一种专门恢复 panic 状态的函数 recover() 。


### recover

recover() 函数作为 Go 内建函数，主要作用是使当前程序重新获得流程控制权。

Go 语言将 recover() 函数定义为一种接口函数，用于解释 panic 异常，定义如下:
```go
    func recover() interface{}
```
该方法的运行机理在于它作为内建函数使得程序恢复对 panic 状态下的协程的管理。

执行过程中 recover() 函数需要在一个 defer 关键字下的函数中运行。

[程序示例](t/07_recover_from_panic.go)
